# Generated by Django 2.2.4 on 2019-08-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
